### ISSUE TITLE
Encoder requires two clicks in opposite direction to register a change in direction

### ISSUE THREAD

**Issue by ilium007** [brianlow/Rotary#11] opened 2020-04-09 02:18 UTC
Encoder library works fine incrementing up or down but when a direction change occurs the first encoder click in the opposite direction doesn't register anything, a second click in the same opposite direction registers an increment in the changed direction.

Code I am using below (basically your example code with SPI OLED screen display added)

```
/**************************************************************************
 This is an example for our Monochrome OLEDs based on SSD1306 drivers

 Pick one up today in the adafruit shop!
 ------> http://www.adafruit.com/category/63_98

 This example is for a 128x64 pixel display using SPI to communicate
 4 or 5 pins are required to interface.

 Adafruit invests time and resources providing this open
 source code, please support Adafruit and open-source
 hardware by purchasing products from Adafruit!

 Written by Limor Fried/Ladyada for Adafruit Industries,
 with contributions from the open source community.
 BSD license, check license.txt for more information
 All text above, and the splash screen below must be
 included in any redistribution.
 **************************************************************************/

#include <SPI.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <Fonts/FreeSansBold24pt7b.h>
#include <Rotary.h>

#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 64 // OLED display height, in pixels

// Comment out above, uncomment this block to use hardware SPI
#define OLED_DC     6
#define OLED_CS     7
#define OLED_RESET  8
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &SPI, OLED_DC, OLED_RESET, OLED_CS);

// Rotary encoder is wired with the common to ground and the two
// outputs to pins 2 and 3.
Rotary rotary = Rotary(2, 3);

// Counter that will be incremented or decremented by rotation.
int counter = 0;

void setup() {
  Serial.begin(57600);
  attachInterrupt(2, rotate, CHANGE);
  attachInterrupt(3, rotate, CHANGE);

  // SSD1306_SWITCHCAPVCC = generate display voltage from 3.3V internally
  if(!display.begin(SSD1306_SWITCHCAPVCC)) {
    Serial.println(F("SSD1306 allocation failed"));
    for(;;); // Don't proceed, loop forever
  }

  // Clear initial display buffer contents on the screen --
  // the library initializes this with an Adafruit splash screen.
  display.clearDisplay();
  display.display();
  display.setFont(&FreeSansBold24pt7b);
}

void loop() {
  
}

void writeNumber(int num) {
  display.clearDisplay();
  display.setCursor(0,48);             // Start at top-left corner
  display.setTextSize(1);             // Draw 2X-scale text
  display.setTextColor(SSD1306_WHITE);
  display.println(num);
  display.display();
}

// rotate is called anytime the rotary inputs change state.
void rotate() {
  unsigned char result = rotary.process();
  if (result == DIR_CW) {
    counter++;
    Serial.print("Counter: ");
    Serial.println(counter);
    //writeNumber(counter);
  } else if (result == DIR_CCW) {
    counter--;
    Serial.print("Counter: ");
    Serial.println(counter);
    //writeNumber(counter);
  }
}
```

**Comment by ilium007** [comment] 2020-05-11 10:21
Realised this only happens when passing the signal through a 74HC14N inverting Schmitt Trigger. No idea why.

**Comment by MortalFool** [comment] 2021-05-17 20:47
I'm running into the same issue when using a rotary encoder with INPUT pins (instead of INPUT_PULLUP pins). Root cause seems to be that the state machine is geared towards being used with the latter, so the values read from pins need to be inverted when used without the internal pullup resistors.

I have created pull request #14 hoping to address this issue.

**Comment by brianlow** [comment] 2021-05-18 17:19
#14 has been merged. Feel free to re-open this issue if still an problem

**Closed by brianlow** 2021-05-18 17:19 UTC
